# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: Generate blog
      run: swift run Blog
    - name: Publish in github pages repo
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        repo: bitomule/blog.bitomule.com
        target_branch: master
        keep_history: true
        allow_empty_commit: false
        build_dir: Output
        committer_name: Bitomule
        commit_message: Update blog content
      env:
        GITHUB_PAT: ${{ secrets.REPO_TOKEN }}
